### ISSUE TITLE
Getting "please provide a frontend username and password" error

### ISSUE THREAD

**Issue by franciscocabral** [jee-r/docker-beets#48]
I followed the readme but I'm getting the following error
```yml
services:
...
  beets:
    image: j33r/beets:latest
    container_name: beets
    restart: unless-stopped
    user: $(id -u):$(id -g)
    ports:
      - 4030:4030
    environment:
      - MODE=betanin
      - BETANIN_HOST="0.0.0.0"
      - BETANIN_PORT=4030
      - WATCH_DIR=/Downloads
      - UMASK_SET=022
      - TZ=America/Sao_Paulo
    volumes:
      - ./beets:/config
      - /data/downloads:/Download
      - /data/media/music:/Music
      - /etc/localtime:/etc/localtime:ro

```

Docker log:
```log
beets  | 2024-09-20 23:01:44.385 | INFO     | betanin.entry.betanin:_ensure_config:61 - using config `/config/.config/betanin/config.toml`
beets  | 2024-09-20 23:01:44.386 | ERROR    | betanin.entry.betanin:_ensure_config:69 - please provide a frontend username and password
beets  | 2024-09-20 23:01:58.405 | INFO     | betanin.entry.betanin:_print_meta_info:34 - platform - Linux-5.15.0-113-generic-x86_64-with
beets  | 2024-09-20 23:01:58.405 | INFO     | betanin.entry.betanin:_print_meta_info:34 - python_version - 3.12.6
beets  | 2024-09-20 23:01:58.405 | INFO     | betanin.entry.betanin:_print_meta_info:34 - betanin_version - v0.5.6
```

There is any way to configure the user and password at the `docker compose up -d`?
